[deps]
Clingo_jll = "e1d4ad0e-dc8b-5d2d-8155-e9a55b531f08"
HerbBenchmarks = "eadf8b74-d38a-4b1a-a063-8d36e493d376"
HerbCore = "2b23ba43-8213-43cb-b5ea-38c12b45bd45"
HerbGrammar = "4ef9e186-2fe5-4b24-8de7-9f7291f24af7"
HerbSearch = "3008d8e8-f9aa-438a-92ed-26e9c7b4829f"
HerbSpecification = "6d54aada-062f-46d8-85cf-a1ceaf058a06"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
