name = "RefactoringExperiments"
uuid = "0fbf8203-857b-4c6b-9279-f5863501e139"

[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Clingo_jll = "e1d4ad0e-dc8b-5d2d-8155-e9a55b531f08"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HerbBenchmarks = "eadf8b74-d38a-4b1a-a063-8d36e493d376"
HerbConstraints = "1fa96474-3206-4513-b4fa-23913f296dfc"
HerbCore = "2b23ba43-8213-43cb-b5ea-38c12b45bd45"
HerbGrammar = "4ef9e186-2fe5-4b24-8de7-9f7291f24af7"
HerbInterpret = "5bbddadd-02c5-4713-84b8-97364418cca7"
HerbSearch = "3008d8e8-f9aa-438a-92ed-26e9c7b4829f"
HerbSpecification = "6d54aada-062f-46d8-85cf-a1ceaf058a06"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Aqua = "0.8.14"
Dates = "1.11.0"
DecisionTree = "0.12.4"
Documenter = "1.16.1"
HerbConstraints = "1.1"
HerbInterpret = "1.0.1"
HerbSearch = "1.0.0"
Test = "1.11.0"
